language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.3
before_install:
  - gem install bundler
before_script:
  - cp config/database.travis.yml config/database.yml
script:
  - bundle exec rake db:create
  - bundle exec rake spec
addons:
  postgresql: "9.4"
services:
  - postgresql